"""empty message

Revision ID: d06fad1d7499
Revises: None
Create Date: 2016-03-11 00:47:58.446740

"""

# revision identifiers, used by Alembic.
revision = 'd06fad1d7499'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'api_key'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('api_secret'),
    sa.UniqueConstraint('id')
    )
    op.create_index('app_index', 'apps', ['api_key'], unique=True)
    op.create_table('auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('activation_code', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('token_created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id', 'install_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('install_id')
    )
    op.create_index('app_auth_install_index', 'auths', ['id', 'app_id', 'install_id'], unique=False)
    op.create_index(op.f('ix_auths_activation_code'), 'auths', ['activation_code'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auths_activation_code'), table_name='auths')
    op.drop_index('app_auth_install_index', table_name='auths')
    op.drop_table('auths')
    op.drop_index('app_index', table_name='apps')
    op.drop_table('apps')
    ### end Alembic commands ###
